<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cma [
  <!ELEMENT cma (prod?, qa?, dev*)>
  <!ELEMENT ip (CDATA) >
  <!ELEMENT prod (ip+) >
  <!ELEMENT qa (ip+) >
  <!ELEMENT dev (ip+) >
  <!ELEMENT port (CDATA) >
  <!ELEMENT prod (port+) >
  <!ELEMENT qa (port+) >
  <!ELEMENT dev (port+) >
]>
<cma>
  <prod>
    <ip>192.168.12.51</ip>
    <port>7030</port>
  </prod>
  <qa>
    <ip>172.16.212.51</ip>
    <port>7030</port>
  </qa>
  <dev>
    <ip>172.16.1.152</ip>
    <port>7030</port>
  </dev>
</cma>
