<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE StatServlet [
        <!ELEMENT StatServlet (RankList?, QuickStatList?, ContentList*,GlobalError)>

        <!ELEMENT RankList (RankItem+) >
        <!ELEMENT RankItem (#PCDATA)>
        <!ATTLIST RankItem minVal CDATA #REQUIRED>
        <!ATTLIST RankItem maxVal CDATA #IMPLIED>

        <!ELEMENT QuickStatList (QuickStatItem+)>

        <!ELEMENT QuickStatItem (#PCDATA)>
        <!ATTLIST QuickStatItem url CDATA #REQUIRED>

        <!ELEMENT ContentList (ContentItem+)>
        <!ELEMENT ContentItem (#PCDATA)>
        <!ATTLIST ContentItem contentHandle CDATA #REQUIRED>
        <!ATTLIST ContentItem nextPage CDATA #REQUIRED>
        <!ATTLIST ContentItem access CDATA #REQUIRED>

        <!ELEMENT GlobalError (#PCDATA)>
        <!ATTLIST GlobalError nextPage CDATA #REQUIRED>
        ]>
<StatServlet>
    <RankList>
        <RankItem minVal="0" maxVal="0">coderTextWhite</RankItem>
        <RankItem minVal="1" maxVal="899">coderTextGray</RankItem>
        <RankItem minVal="900" maxVal="1199">coderTextGreen</RankItem>
        <RankItem minVal="1200" maxVal="1499">coderTextBlue</RankItem>
        <RankItem minVal="1500" maxVal="2199">coderTextYellow</RankItem>
        <RankItem minVal="2200">coderTextRed</RankItem>
    </RankList>
    <QuickStatList>
        <QuickStatItem url="/stat?c=all_time_wins">All-Time Wins</QuickStatItem>
        <QuickStatItem url="/stat?c=consecutive_rating_increases">Consecutive Rating Increases</QuickStatItem>
        <QuickStatItem url="/stat?c=impressive_debuts">Impressive Debuts</QuickStatItem>
        <QuickStatItem url="/stat?c=highest_totals">Highest Total</QuickStatItem>
        <QuickStatItem url="/stat?c=biggest_rating_gains">Rating Point Gain</QuickStatItem>
        <QuickStatItem url="/stat?c=most_consecutive_wins">Consecutive Wins</QuickStatItem>
        <QuickStatItem url="/stat?c=highest_accuracy">Submission Accuracy</QuickStatItem>
        <QuickStatItem url="/stat?c=best_challengers">Challenge Success</QuickStatItem>
        <QuickStatItem url="/stat?c=division_wins">Division Wins</QuickStatItem>
        <QuickStatItem url="/stat?c=rated_events">Rated Events</QuickStatItem>
        <QuickStatItem url="/stat?c=successful_challenges">Most Successful Challenges in a Match</QuickStatItem>
        <QuickStatItem url="/stat?c=consecutive_srm_appearances">Consecutive SRM Appearances</QuickStatItem>
        <QuickStatItem url="/stat?c=most_best_score">Highest Number of Best Score</QuickStatItem>

    </QuickStatList>
    <ContentList>
        <ContentItem contentHandle="all_time_wins" nextPage="/statistics/allTimeWins.jsp" access="0"/>
        <ContentItem contentHandle="all_time_wins_by_div" nextPage="/statistics/allTimeWinsByDiv.jsp" access="0"/>
        <ContentItem contentHandle="winning_debuts" nextPage="/statistics/winDebuts.jsp" access="0"/>
        <ContentItem contentHandle="impressive_debuts" nextPage="/statistics/impressiveDebut.jsp" access="0"/>
        <ContentItem contentHandle="highest_totals" nextPage="/statistics/highTotals.jsp" access="0"/>
        <ContentItem contentHandle="biggest_rating_gains" nextPage="/statistics/ratingGain.jsp" access="0"/>
        <ContentItem contentHandle="most_consecutive_wins" nextPage="/statistics/consecutiveWins.jsp" access="0"/>
        <ContentItem contentHandle="highest_accuracy" nextPage="/statistics/submitAccuracy.jsp" access="0"/>
        <ContentItem contentHandle="best_challengers" nextPage="/statistics/challengeAccuracy.jsp" access="0"/>
        <ContentItem contentHandle="round_stats" nextPage="/statistics/roundStats.jsp" access="0"/>
        <ContentItem contentHandle="round_stats_sorted" nextPage="/statistics/roundStats.jsp" access="0"/>
        <ContentItem contentHandle="last_match" nextPage="/statistics/roundStats.jsp" access="0"/>
        <ContentItem contentHandle="last_match_sorted" nextPage="/statistics/roundStats.jsp" access="0"/>
        <ContentItem contentHandle="room_stats" nextPage="/statistics/roomStats.jsp" access="1"/>
        <ContentItem contentHandle="problem_statement" nextPage="/statistics/problemStatement.jsp" access="0"/>
        <ContentItem contentHandle="problem_solution" nextPage="/statistics/problemSolution.jsp" access="1"/>
        <ContentItem contentHandle="earnings_history" nextPage="/statistics/earningHistory.jsp" access="1"/>
        <ContentItem contentHandle="component_history" nextPage="/statistics/componentHistory.jsp" access="1"/>
        <ContentItem contentHandle="ratings_history" nextPage="/statistics/ratingHistory.jsp" access="1"/>
        <ContentItem contentHandle="tcs_ratings_history" nextPage="/statistics/tcsRatingHistory.jsp" access="1"/>
        <ContentItem contentHandle="coder_room_stats" nextPage="/statistics/roomStats.jsp" access="1"/>
        <ContentItem contentHandle="coder_ratings" nextPage="/statistics/rankList.jsp" access="0"/>
        <ContentItem contentHandle="member_profile" nextPage="/statistics/memberProfile.jsp" access="0"/>
        <ContentItem contentHandle="round_overview" nextPage="/statistics/roundOverview.jsp" access="0"/>
        <ContentItem contentHandle="school_avg_rating" nextPage="/statistics/topRankedSchools.jsp" access="0"/>
        <ContentItem contentHandle="state_avg_rating" nextPage="/statistics/topRankedStates.jsp" access="0"/>
        <ContentItem contentHandle="country_avg_rating" nextPage="/statistics/topRankedCountries.jsp" access="0"/>
        <ContentItem contentHandle="top_designers" nextPage="/statistics/topRankedDesigners.jsp" access="0"/>
        <ContentItem contentHandle="top_developers" nextPage="/statistics/topRankedDevelopers.jsp" access="0"/>
        <ContentItem contentHandle="top_conceptors" nextPage="/statistics/topRankedPage.jsp" access="0"/>
        <ContentItem contentHandle="top_specificators" nextPage="/statistics/topRankedPage.jsp" access="0"/>
        <ContentItem contentHandle="top_architects" nextPage="/statistics/topRankedPage.jsp" access="0"/>
        <ContentItem contentHandle="top_assemblers" nextPage="/statistics/topRankedPage.jsp" access="0"/>
        <ContentItem contentHandle="top_testers" nextPage="/statistics/topRankedPage.jsp" access="0"/>
        <ContentItem contentHandle="consecutive_rating_increases" nextPage="/statistics/consecutiveRatingIncreases.jsp"
                     access="0"/>
        <ContentItem contentHandle="consecutive_srm_appearances" nextPage="/statistics/consecutiveSRMAppearances.jsp"
                     access="0"/>
        <ContentItem contentHandle="most_best_score" nextPage="/statistics/mostBestScore.jsp"
                     access="0"/>
        <ContentItem contentHandle="reliability_history" nextPage="/statistics/reliabilityHistory.jsp" access="1"/>
        <ContentItem contentHandle="division_wins" nextPage="/statistics/division_wins.jsp" access="0"/>
        <ContentItem contentHandle="srm_division_wins" nextPage="/statistics/srm_division_wins.jsp" access="0"/>
        <ContentItem contentHandle="rated_events" nextPage="/statistics/ratedEvents.jsp" access="0"/>
        <ContentItem contentHandle="successful_challenges" nextPage="/statistics/challengeSuccessByMatch.jsp"
                     access="0"/>
    </ContentList>
    <GlobalError nextPage="/errorPage.jsp"/>
</StatServlet>
